language: go
go:
  - 1.12.x
install:
  # Fetch dependencies
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.17.1
  - GO111MODULE=on go mod download
script:
  - ./configure && make test
  - ./configure && make dep
#  - make docker-all
#  - make docker-push-all



sudo: false
notifications:
  email: false

addons:
  artifacts:
    s3_region: "ap-northeast-1"
    paths:
      - $(git ls-files -o --exclude-standard | tr "\n" ":")
    debug: true
    target-paths: $TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
    bucket: "oauth2-proxy-build"
