language: go
go:
  - 1.12.x
install:
  # Fetch dependencies
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.17.1
  - GO111MODULE=on go mod download
script:
  - ./configure && make test
  - ./configure && make build
  - ./configure && make docker

sudo: false
notifications:
  email: false
