version: 2
jobs:
  test:
    working_directory: ~/myapp
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          command: python -m venv env
      - run:
          command: |
            . env/bin/activate
            
          
  deploy:
    working_directory: ~/myapp
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: python -m venv env
      - run:
          name: Build Docker Image and Push to ECR 
          command: |
            COMMIT_ID=$(echo $CIRCLE_SHA1 | cut -c1-7)
            export AWS_ACCOUNT_ID=755575973821
            . env/bin/activate
            pip install -U awscli awsebcli ebi
            aws configure set aws_access_key_id $PROD_AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $PROD_AWS_SECRET_ACCESS_KEY
            aws ecr get-login --no-include-email --region ap-northeast-1 | /bin/bash
            cd ~/myapp
            chmod +x startup.sh
            docker build -t oauth2-proxy .
            docker tag  oauth2-proxy:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/rundeck/oauth2-proxy:latest            
            docker tag  oauth2-proxy:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/rundeck/oauth2-proxy:$COMMIT_ID
            docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/rundeck/oauth2-proxy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
